CASHRISK = 20
RISKMULTIPLIER = 0.001
#STOCKS_TO_TRADE = ["AAPL", "DIS", "FB", "CRM", "BABA", "CMCSA", "PFE", "UAL", "CSCO", "PYPL", "BAC", "ORCL", "MRK", "NVDA", "GILD", "C", "INTC", "MRVL", "MDLZ", "BA", "V", "JPM"]

STOCKS_TO_TRADE = ["AAPL"]